### PR TITLE
Remove cards on bottom

### PR DESCRIPTION
**Pull request by Manuel-777**
A little thing that was requested many times, scryed cards, or rather, cards that are knowingly on the bottom of the library, should be ignored from the cards odds calculation.

image

In the example I scryed to the bottom: An Island, a Temple of Mystery and a Mystical Dispute.
The only issue is that these cards are entirely removed from the cards left in the library rather than just the odds calculation (we probabaly need to add a separate store for the odds)

### CODE REVIEW

**Comment by Manuel-777** [comment]
Related issue: #419

**Comment by Thaoden** [comment]
At what point in the deck should they be re-added to the calculation though? when you cycled through the whole deck?
What happens when the deck is shuffled?

**Comment by Manuel-777** [comment]
> At what point in the deck should they be re-added to the calculation though? when you cycled through the whole deck?
> What happens when the deck is shuffled?

All of those mentioned situations would work as you would expect, since we are not reacting to annotation events or things like that, we are reading trough the library game objects and finding the ones on the bottom, then removing those in the bottom from the calculation. When you shuffle the library for example, the game objects list from the library is updated and the cards on bottom get updated.

**Comment by Thaoden** [comment]
Fair enough. Also, the case I made with the cycled deck is a non-case, as by then you have full knowledge of the next card...

**Pull request merged**
