### PR TITLE
Renderer util to Typescript

### PR DESCRIPTION
**Pull request by Manuel-777**
Also move it to a more generic `util.ts`, since it lives in `window_main`, it becomes redundant.

### CODE REVIEW

**Comment by lusbenjamin** [comment]
er, seems redundant with #929?

**Comment by Manuel-777** [comment]
> er, seems redundant with #929?

>.>

<.<

**Comment by lusbenjamin** [comment]
Actually now that I look at it, you had some more precise types, particularly around `WinLoss` gates.

**Comment by lusbenjamin** [comment]
Also, only having a single `util` not a bad idea.

**Comment by Manuel-777** [comment]
Feel free to copypasta those!

**Pull request closed without merging**
